[package]
name = "inferencers"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.3"
tokio = { version = "1.41.0", features = ["full"] }
tonic = "0.12.3"

[build-dependencies]
tonic-build = { version = "0.12.3", features = ["prost"] }
